// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 03e84f604d558643 "Radison (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'first cycle' | 'second cycle' | 'third cycle' | 'last cycle' // Variant
}} Props

 */
import { routes } from "../chunks/chunk-HNSAVAZ4.js";

// virtual:cards/bar-chart-animation
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/vKV63PIFb3pgAt5omeZC/xAASGE0BnUChWpoKYyQH/IFsGGHyuV.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	CycleVariantState,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useOnVariantChange,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var cycleOrder = ["ZaWK82YPf", "Hxl4nFoHc", "TKUQfTwLN", "YqS3gkRRW"];
var serializationHash = "framer-zQxPl";
var variantClassNames = {
	Hxl4nFoHc: "framer-v-kqtk2r",
	TKUQfTwLN: "framer-v-a88509",
	YqS3gkRRW: "framer-v-6730me",
	ZaWK82YPf: "framer-v-1ftmz4p",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transition1 = {
	damping: 70,
	delay: 0,
	mass: 1,
	stiffness: 300,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"first cycle": "ZaWK82YPf",
	"last cycle": "YqS3gkRRW",
	"second cycle": "Hxl4nFoHc",
	"third cycle": "TKUQfTwLN",
};
var getProps = ({ height, id, width, ...props }) => {
	var _humanReadableVariantMap_props_variant, _ref;
	return {
		...props,
		variant:
			(_ref =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref !== void 0
				? _ref
				: "ZaWK82YPf",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "ZaWK82YPf",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onAppear1a2vbif = activeVariantCallback(async (...args) => {
		await delay(() => setVariant(CycleVariantState), 1500);
	});
	const onAppearf382t5 = activeVariantCallback(async (...args) => {
		await delay(() => setVariant(CycleVariantState), 2e3);
	});
	useOnVariantChange(baseVariant, {
		default: onAppear1a2vbif,
		Hxl4nFoHc: onAppearf382t5,
		TKUQfTwLN: onAppearf382t5,
		YqS3gkRRW: onAppearf382t5,
	});
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							serializationHash,
							...sharedStyleClassNames,
							"framer-1ftmz4p",
							className,
							classNames,
						)}
						data-framer-name={"first cycle"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"ZaWK82YPf"}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								Hxl4nFoHc: {
									"data-framer-name": "second cycle",
								},
								TKUQfTwLN: {
									"data-framer-name": "third cycle",
								},
								YqS3gkRRW: {
									"data-framer-name": "last cycle",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1iashoj"}
							data-framer-name={"Bar1"}
							layoutDependency={layoutDependency}
							layoutId={"vx5tY4flZ"}
							style={{
								backgroundColor:
									"var(--token-667dfe34-ef33-4a0e-b107-e347ef5ffaa2, rgba(255, 255, 255, 0.15))",
								borderTopLeftRadius: 1,
								borderTopRightRadius: 1,
							}}
						>
							<motion.div
								className={"framer-1i9b5md"}
								data-framer-name={"Blue filled"}
								layoutDependency={layoutDependency}
								layoutId={"ncyS9EhAe"}
								style={{
									backgroundColor:
										"var(--token-161a5f1c-45d6-4b0d-83c5-2f276392762e, rgba(81, 47, 235, 0.7))",
								}}
							/>
						</motion.div>
						<motion.div
							className={"framer-1lbsk0g"}
							data-framer-name={"Bar2"}
							layoutDependency={layoutDependency}
							layoutId={"cU0J3sK88"}
							style={{
								backgroundColor:
									"var(--token-667dfe34-ef33-4a0e-b107-e347ef5ffaa2, rgba(255, 255, 255, 0.15))",
								borderTopLeftRadius: 1,
								borderTopRightRadius: 1,
							}}
						>
							<motion.div
								className={"framer-55adu9"}
								data-framer-name={"Blue filled"}
								layoutDependency={layoutDependency}
								layoutId={"yNP1ZDN0D"}
								style={{
									backgroundColor:
										"var(--token-161a5f1c-45d6-4b0d-83c5-2f276392762e, rgba(81, 47, 235, 0.7))",
								}}
							/>
						</motion.div>
						<motion.div
							className={"framer-1baun43"}
							data-framer-name={"Bar3"}
							layoutDependency={layoutDependency}
							layoutId={"urDV698ag"}
							style={{
								backgroundColor: "rgba(255, 255, 255, 0.12)",
								borderTopLeftRadius: 1,
								borderTopRightRadius: 1,
							}}
						>
							<motion.div
								className={"framer-ibsi85"}
								data-framer-name={"Blue filled"}
								layoutDependency={layoutDependency}
								layoutId={"yFUtcqDMc"}
								style={{
									backgroundColor:
										"var(--token-161a5f1c-45d6-4b0d-83c5-2f276392762e, rgba(81, 47, 235, 0.7))",
								}}
							/>
						</motion.div>
						<motion.div
							className={"framer-1qaajsd"}
							data-framer-name={"Bar4"}
							layoutDependency={layoutDependency}
							layoutId={"DveyN39ju"}
							style={{
								backgroundColor:
									"var(--token-667dfe34-ef33-4a0e-b107-e347ef5ffaa2, rgba(255, 255, 255, 0.15))",
								borderTopLeftRadius: 1,
								borderTopRightRadius: 1,
							}}
						>
							<motion.div
								className={"framer-136du0i"}
								data-framer-name={"Blue filled"}
								layoutDependency={layoutDependency}
								layoutId={"Zr33CFVo8"}
								style={{
									backgroundColor:
										"var(--token-161a5f1c-45d6-4b0d-83c5-2f276392762e, rgba(81, 47, 235, 0.7))",
								}}
							/>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-zQxPl.framer-rbxa96, .framer-zQxPl .framer-rbxa96 { display: block; }",
	".framer-zQxPl.framer-1ftmz4p { align-content: flex-end; align-items: flex-end; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 7px; height: 50px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-zQxPl .framer-1iashoj { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 20px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 8px; will-change: var(--framer-will-change-override, transform); }",
	".framer-zQxPl .framer-1i9b5md { bottom: -25px; flex: none; height: 20px; left: calc(50.00000000000002% - 8px / 2); overflow: visible; position: absolute; width: 8px; z-index: 1; }",
	".framer-zQxPl .framer-1lbsk0g { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 10px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 8px; will-change: var(--framer-will-change-override, transform); }",
	".framer-zQxPl .framer-55adu9 { bottom: -15px; flex: none; height: 10px; left: calc(50.00000000000002% - 8px / 2); overflow: visible; position: absolute; width: 8px; z-index: 1; }",
	".framer-zQxPl .framer-1baun43 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 25px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 8px; will-change: var(--framer-will-change-override, transform); }",
	".framer-zQxPl .framer-ibsi85 { bottom: 0px; flex: none; height: 25px; left: calc(50.00000000000002% - 8px / 2); overflow: visible; position: absolute; width: 8px; z-index: 1; }",
	".framer-zQxPl .framer-1qaajsd { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 30px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 8px; will-change: var(--framer-will-change-override, transform); }",
	".framer-zQxPl .framer-136du0i { bottom: -35px; flex: none; height: 30px; left: calc(50.00000000000002% - 8px / 2); overflow: visible; position: absolute; width: 8px; z-index: 1; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-zQxPl.framer-1ftmz4p, .framer-zQxPl .framer-1iashoj, .framer-zQxPl .framer-1lbsk0g, .framer-zQxPl .framer-1baun43, .framer-zQxPl .framer-1qaajsd { gap: 0px; } .framer-zQxPl.framer-1ftmz4p > * { margin: 0px; margin-left: calc(7px / 2); margin-right: calc(7px / 2); } .framer-zQxPl.framer-1ftmz4p > :first-child { margin-left: 0px; } .framer-zQxPl.framer-1ftmz4p > :last-child { margin-right: 0px; } .framer-zQxPl .framer-1iashoj > *, .framer-zQxPl .framer-1lbsk0g > *, .framer-zQxPl .framer-1baun43 > *, .framer-zQxPl .framer-1qaajsd > * { margin: 0px; margin-bottom: calc(10px / 2); margin-top: calc(10px / 2); } .framer-zQxPl .framer-1iashoj > :first-child, .framer-zQxPl .framer-1lbsk0g > :first-child, .framer-zQxPl .framer-1baun43 > :first-child, .framer-zQxPl .framer-1qaajsd > :first-child { margin-top: 0px; } .framer-zQxPl .framer-1iashoj > :last-child, .framer-zQxPl .framer-1lbsk0g > :last-child, .framer-zQxPl .framer-1baun43 > :last-child, .framer-zQxPl .framer-1qaajsd > :last-child { margin-bottom: 0px; } }",
	".framer-zQxPl.framer-v-kqtk2r .framer-1i9b5md, .framer-zQxPl.framer-v-a88509 .framer-136du0i, .framer-zQxPl.framer-v-6730me .framer-55adu9 { bottom: 0px; }",
	".framer-zQxPl.framer-v-kqtk2r .framer-ibsi85, .framer-zQxPl.framer-v-a88509 .framer-ibsi85, .framer-zQxPl.framer-v-6730me .framer-ibsi85 { bottom: -30px; }",
];
var FramerIFsGGHyuV = withCSS(Component, css, "framer-zQxPl");
var stdin_default = FramerIFsGGHyuV;
FramerIFsGGHyuV.displayName = "Cards/ Bar chart animation";
FramerIFsGGHyuV.defaultProps = {
	height: 50,
	width: 53,
};
addPropertyControls(FramerIFsGGHyuV, {
	variant: {
		options: ["ZaWK82YPf", "Hxl4nFoHc", "TKUQfTwLN", "YqS3gkRRW"],
		optionTitles: ["first cycle", "second cycle", "third cycle", "last cycle"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerIFsGGHyuV,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:cards/bar-chart-animation
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "ZaWK82YPf",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"03e84f604d558643c3b6be5341937b8855a6dbf7a820b887c6c5c1f3ad48ac5b"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders BarChartAnimationFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"03e84f604d558643c3b6be5341937b8855a6dbf7a820b887c6c5c1f3ad48ac5b"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var bar_chart_animation_default = ComponentWithRoot;
export { bar_chart_animation_default as default };
