// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 03e84f604d558643 "Radison (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Text' | 'Empty' // Variant
}} Props

 */
import { routes } from "../chunks/chunk-HNSAVAZ4.js";

// virtual:cards/code-animation
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/1DAut5NIKJ3u3W03VoVu/mrdBtv6zSXJSp4IcUcjQ/cribsgnSU.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	CycleVariantState,
	RichText,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useOnVariantChange,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var cycleOrder = ["NUtWSUHgD", "GE4qRZXiM"];
var serializationHash = "framer-A2rJT";
var variantClassNames = {
	GE4qRZXiM: "framer-v-6lkvee",
	NUtWSUHgD: "framer-v-3rkuc9",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var animation = {
	opacity: 1e-3,
	rotate: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 10,
};
var transition2 = {
	bounce: 0,
	delay: 0.075,
	duration: 0.4,
	type: "spring",
};
var textEffect = {
	effect: animation,
	repeat: true,
	threshold: 0.5,
	tokenization: "word",
	transition: transition2,
	trigger: "onInView",
	type: "appear",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Empty: "GE4qRZXiM",
	Text: "NUtWSUHgD",
};
var getProps = ({ height, id, width, ...props }) => {
	var _humanReadableVariantMap_props_variant, _ref;
	return {
		...props,
		variant:
			(_ref =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref !== void 0
				? _ref
				: "NUtWSUHgD",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "NUtWSUHgD",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onAppear181773e = activeVariantCallback(async (...args) => {
		await delay(() => setVariant(CycleVariantState), 4800);
	});
	const onAppear7vqrr5 = activeVariantCallback(async (...args) => {
		await delay(() => setVariant(CycleVariantState), 500);
	});
	useOnVariantChange(baseVariant, {
		default: onAppear181773e,
		GE4qRZXiM: onAppear7vqrr5,
	});
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							serializationHash,
							...sharedStyleClassNames,
							"framer-3rkuc9",
							className,
							classNames,
						)}
						data-framer-name={"Text"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"NUtWSUHgD"}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								GE4qRZXiM: {
									"data-framer-name": "Empty",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-172a42j"}
							effect={textEffect}
							fonts={["FS;Outfit-light"]}
							layoutDependency={layoutDependency}
							layoutId={"ymZerdh6M"}
							style={{
								"--extracted-10pia13":
									"var(--token-161a5f1c-45d6-4b0d-83c5-2f276392762e, rgba(81, 47, 235, 0.7))",
								"--extracted-14qxiz":
									"var(--token-8c14519b-b926-46e8-8772-9a05cbede172, rgba(255, 255, 255, 0.7))",
								"--extracted-164ca6r":
									"var(--token-161a5f1c-45d6-4b0d-83c5-2f276392762e, rgba(81, 47, 235, 0.7))",
								"--extracted-1iakedh":
									"var(--token-8c14519b-b926-46e8-8772-9a05cbede172, rgba(255, 255, 255, 0.7))",
								"--extracted-1yfvjw7":
									"var(--token-8c14519b-b926-46e8-8772-9a05cbede172, rgba(255, 255, 255, 0.7))",
								"--extracted-2gxw0f":
									"var(--token-8c14519b-b926-46e8-8772-9a05cbede172, rgba(255, 255, 255, 0.7))",
								"--extracted-8vgz36":
									"var(--token-8c14519b-b926-46e8-8772-9a05cbede172, rgba(255, 255, 255, 0.7))",
								"--extracted-r6o4lv":
									"var(--token-8c14519b-b926-46e8-8772-9a05cbede172, rgba(255, 255, 255, 0.7))",
								"--extracted-t2ptvp":
									"var(--token-8c14519b-b926-46e8-8772-9a05cbede172, rgba(255, 255, 255, 0.7))",
								"--extracted-ydz9fi":
									"var(--token-8c14519b-b926-46e8-8772-9a05cbede172, rgba(255, 255, 255, 0.7))",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							variants={{
								GE4qRZXiM: {
									"--extracted-tcooor": "rgba(255, 255, 255, 0.7)",
								},
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
							{...addPropertyOverrides(
								{
									GE4qRZXiM: {
										children: (
											<React.Fragment>
												<motion.div
													style={{
														"--font-selector": "RlM7U2F0b3NoaS1yZWd1bGFy",
														"--framer-font-family":
															'"Satoshi", "Satoshi Placeholder", sans-serif',
														"--framer-font-size": "10px",
														"--framer-letter-spacing": "-0.04em",
														"--framer-line-height": "1.7em",
														"--framer-text-color":
															"var(--extracted-tcooor, rgba(255, 255, 255, 0.7))",
													}}
												>
													<motion.br className={"trailing-break"} />
												</motion.div>
											</React.Fragment>
										),
										effect: void 0,
										fonts: ["FS;Satoshi-regular"],
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<React.Fragment>
								<motion.p
									style={{
										"--font-selector": "RlM7T3V0Zml0LWxpZ2h0",
										"--framer-font-family":
											'"Outfit", "Outfit Placeholder", sans-serif',
										"--framer-font-size": "10px",
										"--framer-font-weight": "300",
										"--framer-letter-spacing": "-0.04em",
										"--framer-line-height": "1.7em",
										"--framer-text-color":
											"var(--extracted-r6o4lv, var(--token-8c14519b-b926-46e8-8772-9a05cbede172, rgba(255, 255, 255, 0.7)))",
									}}
								>
									<motion.code>
										<motion.span
											style={{
												"--framer-text-color":
													"var(--extracted-164ca6r, var(--token-161a5f1c-45d6-4b0d-83c5-2f276392762e, rgba(81, 47, 235, 0.7)))",
											}}
										>
											{"class"}
										</motion.span>
									</motion.code>{" "}
									<motion.code>{"Sampling(layers.Layer):"}</motion.code>
								</motion.p>
								<motion.p
									style={{
										"--font-selector": "RlM7T3V0Zml0LWxpZ2h0",
										"--framer-font-family":
											'"Outfit", "Outfit Placeholder", sans-serif',
										"--framer-font-size": "10px",
										"--framer-font-weight": "300",
										"--framer-letter-spacing": "-0.04em",
										"--framer-line-height": "1.7em",
										"--framer-text-color":
											"var(--extracted-2gxw0f, var(--token-8c14519b-b926-46e8-8772-9a05cbede172, rgba(255, 255, 255, 0.7)))",
									}}
								>
									<motion.code>
										{
											'\xA0\xA0\xA0\xA0"""Uses (mean, log_var) to sample z, the vector encoding a digit."""'
										}
									</motion.code>
								</motion.p>
								<motion.p
									style={{
										"--font-selector": "RlM7T3V0Zml0LWxpZ2h0",
										"--framer-font-family":
											'"Outfit", "Outfit Placeholder", sans-serif',
										"--framer-font-size": "10px",
										"--framer-font-weight": "300",
										"--framer-letter-spacing": "-0.04em",
										"--framer-line-height": "1.7em",
										"--framer-text-color":
											"var(--extracted-1iakedh, var(--token-8c14519b-b926-46e8-8772-9a05cbede172, rgba(255, 255, 255, 0.7)))",
									}}
								>
									{"\xA0"}
								</motion.p>
								<motion.p
									style={{
										"--font-selector": "RlM7T3V0Zml0LWxpZ2h0",
										"--framer-font-family":
											'"Outfit", "Outfit Placeholder", sans-serif',
										"--framer-font-size": "10px",
										"--framer-font-weight": "300",
										"--framer-letter-spacing": "-0.04em",
										"--framer-line-height": "1.7em",
										"--framer-text-color":
											"var(--extracted-14qxiz, var(--token-8c14519b-b926-46e8-8772-9a05cbede172, rgba(255, 255, 255, 0.7)))",
									}}
								>
									<motion.code>
										{"\xA0\xA0\xA0\xA0"}
										<motion.span
											style={{
												"--framer-text-color":
													"var(--extracted-10pia13, var(--token-161a5f1c-45d6-4b0d-83c5-2f276392762e, rgba(81, 47, 235, 0.7)))",
											}}
										>
											{"def"}
										</motion.span>
									</motion.code>{" "}
									<motion.code>{"call(self, inputs):"}</motion.code>
								</motion.p>
								<motion.p
									style={{
										"--font-selector": "RlM7T3V0Zml0LWxpZ2h0",
										"--framer-font-family":
											'"Outfit", "Outfit Placeholder", sans-serif',
										"--framer-font-size": "10px",
										"--framer-font-weight": "300",
										"--framer-letter-spacing": "-0.04em",
										"--framer-line-height": "1.7em",
										"--framer-text-color":
											"var(--extracted-ydz9fi, var(--token-8c14519b-b926-46e8-8772-9a05cbede172, rgba(255, 255, 255, 0.7)))",
									}}
								>
									<motion.code>
										{"\xA0\xA0\xA0\xA0\xA0\xA0\xA0\xA0mean, log_var ="}
									</motion.code>{" "}
									<motion.code>{"inputs"}</motion.code>
								</motion.p>
								<motion.p
									style={{
										"--font-selector": "RlM7T3V0Zml0LWxpZ2h0",
										"--framer-font-family":
											'"Outfit", "Outfit Placeholder", sans-serif',
										"--framer-font-size": "10px",
										"--framer-font-weight": "300",
										"--framer-letter-spacing": "-0.04em",
										"--framer-line-height": "1.7em",
										"--framer-text-color":
											"var(--extracted-1yfvjw7, var(--token-8c14519b-b926-46e8-8772-9a05cbede172, rgba(255, 255, 255, 0.7)))",
									}}
								>
									<motion.code>
										{"\xA0\xA0\xA0\xA0\xA0\xA0\xA0\xA0batch ="}
									</motion.code>{" "}
									<motion.code>{"tf.shape(mean)[0]"}</motion.code>
								</motion.p>
								<motion.p
									style={{
										"--font-selector": "RlM7T3V0Zml0LWxpZ2h0",
										"--framer-font-family":
											'"Outfit", "Outfit Placeholder", sans-serif',
										"--framer-font-size": "10px",
										"--framer-font-weight": "300",
										"--framer-letter-spacing": "-0.04em",
										"--framer-line-height": "1.7em",
										"--framer-text-color":
											"var(--extracted-8vgz36, var(--token-8c14519b-b926-46e8-8772-9a05cbede172, rgba(255, 255, 255, 0.7)))",
									}}
								>
									<motion.code>
										{"\xA0\xA0\xA0\xA0\xA0\xA0\xA0\xA0dim ="}
									</motion.code>{" "}
									<motion.code>{"tf.shape(mean)[1]"}</motion.code>
								</motion.p>
								<motion.p
									style={{
										"--font-selector": "RlM7T3V0Zml0LWxpZ2h0",
										"--framer-font-family":
											'"Outfit", "Outfit Placeholder", sans-serif',
										"--framer-font-size": "10px",
										"--framer-font-weight": "300",
										"--framer-letter-spacing": "-0.04em",
										"--framer-line-height": "1.7em",
										"--framer-text-color":
											"var(--extracted-t2ptvp, var(--token-8c14519b-b926-46e8-8772-9a05cbede172, rgba(255, 255, 255, 0.7)))",
									}}
								>
									<motion.code>
										{"\xA0\xA0\xA0\xA0\xA0\xA0\xA0\xA0return"}
									</motion.code>{" "}
									<motion.code>{"mean +"}</motion.code>{" "}
									<motion.code>{"tf.exp(0.5"}</motion.code>{" "}
									<motion.code>{"*"}</motion.code>{" "}
									<motion.code>{"log_var) *"}</motion.code>{" "}
									<motion.code>{"epsilon"}</motion.code>
								</motion.p>
							</React.Fragment>
						</RichText>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-A2rJT.framer-u5q2zy, .framer-A2rJT .framer-u5q2zy { display: block; }",
	".framer-A2rJT.framer-3rkuc9 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 180px; }",
	".framer-A2rJT .framer-172a42j { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-A2rJT.framer-3rkuc9 { gap: 0px; } .framer-A2rJT.framer-3rkuc9 > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-A2rJT.framer-3rkuc9 > :first-child { margin-left: 0px; } .framer-A2rJT.framer-3rkuc9 > :last-child { margin-right: 0px; } }",
];
var FramercribsgnSU = withCSS(Component, css, "framer-A2rJT");
var stdin_default = FramercribsgnSU;
FramercribsgnSU.displayName = "Cards/ Code animation";
FramercribsgnSU.defaultProps = {
	height: 170,
	width: 180,
};
addPropertyControls(FramercribsgnSU, {
	variant: {
		options: ["NUtWSUHgD", "GE4qRZXiM"],
		optionTitles: ["Text", "Empty"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramercribsgnSU,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Outfit",
					source: "fontshare",
					style: "normal",
					url: "https://framerusercontent.com/third-party-assets/fontshare/wf/HGVZO4W7MOWSOT5FITRR2LXJL4LPEVKA/JGNFYTACJN27RPO2O5AUTRRZD4FNRJPI/W7JHARPQSG6P4YAUJKIMUM6JNAX2RFW3.woff2",
					weight: "300",
				},
				{
					family: "Satoshi",
					source: "fontshare",
					style: "normal",
					url: "https://framerusercontent.com/third-party-assets/fontshare/wf/TTX2Z3BF3P6Y5BQT3IV2VNOK6FL22KUT/7QYRJOI3JIMYHGY6CH7SOIFRQLZOLNJ6/KFIAZD4RUMEZIYV6FQ3T3GP5PDBDB6JY.woff2",
					weight: "400",
				},
			],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:cards/code-animation
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "NUtWSUHgD",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"03e84f604d558643c3b6be5341937b8855a6dbf7a820b887c6c5c1f3ad48ac5b"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders CodeAnimationFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"03e84f604d558643c3b6be5341937b8855a6dbf7a820b887c6c5c1f3ad48ac5b"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var code_animation_default = ComponentWithRoot;
export { code_animation_default as default };
