// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 03e84f604d558643 "Radison (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { routes } from "./chunks/chunk-HNSAVAZ4.js";

// virtual:development-card
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/leh2tspMHyu9XprfMQNM/qxm65tw95UaQOxjkPHpt/S9RrCB1zs.js
import { jsx as _jsx2, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	ComponentViewportProvider,
	cx as cx2,
	getFonts,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";

// /:https://framerusercontent.com/modules/NGTpPNa0t6zfiqsy1Ruo/Qa6pRNam3WhKe7uZ0jMm/cribsgnSU.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	CycleVariantState,
	RichText,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useOnVariantChange,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var cycleOrder = ["NUtWSUHgD", "GE4qRZXiM"];
var serializationHash = "framer-A2rJT";
var variantClassNames = {
	GE4qRZXiM: "framer-v-6lkvee",
	NUtWSUHgD: "framer-v-3rkuc9",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var animation = {
	opacity: 1e-3,
	rotate: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 10,
};
var transition2 = {
	bounce: 0,
	delay: 0.075,
	duration: 0.4,
	type: "spring",
};
var textEffect = {
	effect: animation,
	repeat: true,
	threshold: 0.5,
	tokenization: "word",
	transition: transition2,
	trigger: "onInView",
	type: "appear",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Empty: "GE4qRZXiM",
	Text: "NUtWSUHgD",
};
var getProps = ({ height, id, width, ...props }) => {
	var _humanReadableVariantMap_props_variant, _ref;
	return {
		...props,
		variant:
			(_ref =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref !== void 0
				? _ref
				: "NUtWSUHgD",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "NUtWSUHgD",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onAppear181773e = activeVariantCallback(async (...args) => {
		await delay(() => setVariant(CycleVariantState), 4800);
	});
	const onAppear7vqrr5 = activeVariantCallback(async (...args) => {
		await delay(() => setVariant(CycleVariantState), 500);
	});
	useOnVariantChange(baseVariant, {
		default: onAppear181773e,
		GE4qRZXiM: onAppear7vqrr5,
	});
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							serializationHash,
							...sharedStyleClassNames,
							"framer-3rkuc9",
							className,
							classNames,
						)}
						data-framer-name={"Text"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"NUtWSUHgD"}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								GE4qRZXiM: {
									"data-framer-name": "Empty",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-172a42j"}
							effect={textEffect}
							fonts={["FS;Outfit-light"]}
							layoutDependency={layoutDependency}
							layoutId={"ymZerdh6M"}
							style={{
								"--extracted-10pia13":
									"var(--token-161a5f1c-45d6-4b0d-83c5-2f276392762e, rgba(81, 47, 235, 0.7))",
								"--extracted-14qxiz":
									"var(--token-8c14519b-b926-46e8-8772-9a05cbede172, rgba(255, 255, 255, 0.7))",
								"--extracted-164ca6r":
									"var(--token-161a5f1c-45d6-4b0d-83c5-2f276392762e, rgba(81, 47, 235, 0.7))",
								"--extracted-1iakedh":
									"var(--token-8c14519b-b926-46e8-8772-9a05cbede172, rgba(255, 255, 255, 0.7))",
								"--extracted-1yfvjw7":
									"var(--token-8c14519b-b926-46e8-8772-9a05cbede172, rgba(255, 255, 255, 0.7))",
								"--extracted-2gxw0f":
									"var(--token-8c14519b-b926-46e8-8772-9a05cbede172, rgba(255, 255, 255, 0.7))",
								"--extracted-8vgz36":
									"var(--token-8c14519b-b926-46e8-8772-9a05cbede172, rgba(255, 255, 255, 0.7))",
								"--extracted-r6o4lv":
									"var(--token-8c14519b-b926-46e8-8772-9a05cbede172, rgba(255, 255, 255, 0.7))",
								"--extracted-t2ptvp":
									"var(--token-8c14519b-b926-46e8-8772-9a05cbede172, rgba(255, 255, 255, 0.7))",
								"--extracted-ydz9fi":
									"var(--token-8c14519b-b926-46e8-8772-9a05cbede172, rgba(255, 255, 255, 0.7))",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							variants={{
								GE4qRZXiM: {
									"--extracted-tcooor": "rgba(255, 255, 255, 0.7)",
								},
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
							{...addPropertyOverrides(
								{
									GE4qRZXiM: {
										children: (
											<React.Fragment>
												<motion.div
													style={{
														"--font-selector": "RlM7U2F0b3NoaS1yZWd1bGFy",
														"--framer-font-family":
															'"Satoshi", "Satoshi Placeholder", sans-serif',
														"--framer-font-size": "10px",
														"--framer-letter-spacing": "-0.04em",
														"--framer-line-height": "1.7em",
														"--framer-text-color":
															"var(--extracted-tcooor, rgba(255, 255, 255, 0.7))",
													}}
												>
													<motion.br className={"trailing-break"} />
												</motion.div>
											</React.Fragment>
										),
										effect: void 0,
										fonts: ["FS;Satoshi-regular"],
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<React.Fragment>
								<motion.p
									style={{
										"--font-selector": "RlM7T3V0Zml0LWxpZ2h0",
										"--framer-font-family":
											'"Outfit", "Outfit Placeholder", sans-serif',
										"--framer-font-size": "10px",
										"--framer-font-weight": "300",
										"--framer-letter-spacing": "-0.04em",
										"--framer-line-height": "1.7em",
										"--framer-text-color":
											"var(--extracted-r6o4lv, var(--token-8c14519b-b926-46e8-8772-9a05cbede172, rgba(255, 255, 255, 0.7)))",
									}}
								>
									<motion.code>
										<motion.span
											style={{
												"--framer-text-color":
													"var(--extracted-164ca6r, var(--token-161a5f1c-45d6-4b0d-83c5-2f276392762e, rgba(81, 47, 235, 0.7)))",
											}}
										>
											{"class"}
										</motion.span>
									</motion.code>{" "}
									<motion.code>{"Sampling(layers.Layer):"}</motion.code>
								</motion.p>
								<motion.p
									style={{
										"--font-selector": "RlM7T3V0Zml0LWxpZ2h0",
										"--framer-font-family":
											'"Outfit", "Outfit Placeholder", sans-serif',
										"--framer-font-size": "10px",
										"--framer-font-weight": "300",
										"--framer-letter-spacing": "-0.04em",
										"--framer-line-height": "1.7em",
										"--framer-text-color":
											"var(--extracted-2gxw0f, var(--token-8c14519b-b926-46e8-8772-9a05cbede172, rgba(255, 255, 255, 0.7)))",
									}}
								>
									<motion.code>
										{
											'\xA0\xA0\xA0\xA0"""Uses (mean, log_var) to sample z, the vector encoding a digit."""'
										}
									</motion.code>
								</motion.p>
								<motion.p
									style={{
										"--font-selector": "RlM7T3V0Zml0LWxpZ2h0",
										"--framer-font-family":
											'"Outfit", "Outfit Placeholder", sans-serif',
										"--framer-font-size": "10px",
										"--framer-font-weight": "300",
										"--framer-letter-spacing": "-0.04em",
										"--framer-line-height": "1.7em",
										"--framer-text-color":
											"var(--extracted-1iakedh, var(--token-8c14519b-b926-46e8-8772-9a05cbede172, rgba(255, 255, 255, 0.7)))",
									}}
								>
									{"\xA0"}
								</motion.p>
								<motion.p
									style={{
										"--font-selector": "RlM7T3V0Zml0LWxpZ2h0",
										"--framer-font-family":
											'"Outfit", "Outfit Placeholder", sans-serif',
										"--framer-font-size": "10px",
										"--framer-font-weight": "300",
										"--framer-letter-spacing": "-0.04em",
										"--framer-line-height": "1.7em",
										"--framer-text-color":
											"var(--extracted-14qxiz, var(--token-8c14519b-b926-46e8-8772-9a05cbede172, rgba(255, 255, 255, 0.7)))",
									}}
								>
									<motion.code>
										{"\xA0\xA0\xA0\xA0"}
										<motion.span
											style={{
												"--framer-text-color":
													"var(--extracted-10pia13, var(--token-161a5f1c-45d6-4b0d-83c5-2f276392762e, rgba(81, 47, 235, 0.7)))",
											}}
										>
											{"def"}
										</motion.span>
									</motion.code>{" "}
									<motion.code>{"call(self, inputs):"}</motion.code>
								</motion.p>
								<motion.p
									style={{
										"--font-selector": "RlM7T3V0Zml0LWxpZ2h0",
										"--framer-font-family":
											'"Outfit", "Outfit Placeholder", sans-serif',
										"--framer-font-size": "10px",
										"--framer-font-weight": "300",
										"--framer-letter-spacing": "-0.04em",
										"--framer-line-height": "1.7em",
										"--framer-text-color":
											"var(--extracted-ydz9fi, var(--token-8c14519b-b926-46e8-8772-9a05cbede172, rgba(255, 255, 255, 0.7)))",
									}}
								>
									<motion.code>
										{"\xA0\xA0\xA0\xA0\xA0\xA0\xA0\xA0mean, log_var ="}
									</motion.code>{" "}
									<motion.code>{"inputs"}</motion.code>
								</motion.p>
								<motion.p
									style={{
										"--font-selector": "RlM7T3V0Zml0LWxpZ2h0",
										"--framer-font-family":
											'"Outfit", "Outfit Placeholder", sans-serif',
										"--framer-font-size": "10px",
										"--framer-font-weight": "300",
										"--framer-letter-spacing": "-0.04em",
										"--framer-line-height": "1.7em",
										"--framer-text-color":
											"var(--extracted-1yfvjw7, var(--token-8c14519b-b926-46e8-8772-9a05cbede172, rgba(255, 255, 255, 0.7)))",
									}}
								>
									<motion.code>
										{"\xA0\xA0\xA0\xA0\xA0\xA0\xA0\xA0batch ="}
									</motion.code>{" "}
									<motion.code>{"tf.shape(mean)[0]"}</motion.code>
								</motion.p>
								<motion.p
									style={{
										"--font-selector": "RlM7T3V0Zml0LWxpZ2h0",
										"--framer-font-family":
											'"Outfit", "Outfit Placeholder", sans-serif',
										"--framer-font-size": "10px",
										"--framer-font-weight": "300",
										"--framer-letter-spacing": "-0.04em",
										"--framer-line-height": "1.7em",
										"--framer-text-color":
											"var(--extracted-8vgz36, var(--token-8c14519b-b926-46e8-8772-9a05cbede172, rgba(255, 255, 255, 0.7)))",
									}}
								>
									<motion.code>
										{"\xA0\xA0\xA0\xA0\xA0\xA0\xA0\xA0dim ="}
									</motion.code>{" "}
									<motion.code>{"tf.shape(mean)[1]"}</motion.code>
								</motion.p>
								<motion.p
									style={{
										"--font-selector": "RlM7T3V0Zml0LWxpZ2h0",
										"--framer-font-family":
											'"Outfit", "Outfit Placeholder", sans-serif',
										"--framer-font-size": "10px",
										"--framer-font-weight": "300",
										"--framer-letter-spacing": "-0.04em",
										"--framer-line-height": "1.7em",
										"--framer-text-color":
											"var(--extracted-t2ptvp, var(--token-8c14519b-b926-46e8-8772-9a05cbede172, rgba(255, 255, 255, 0.7)))",
									}}
								>
									<motion.code>
										{"\xA0\xA0\xA0\xA0\xA0\xA0\xA0\xA0return"}
									</motion.code>{" "}
									<motion.code>{"mean +"}</motion.code>{" "}
									<motion.code>{"tf.exp(0.5"}</motion.code>{" "}
									<motion.code>{"*"}</motion.code>{" "}
									<motion.code>{"log_var) *"}</motion.code>{" "}
									<motion.code>{"epsilon"}</motion.code>
								</motion.p>
							</React.Fragment>
						</RichText>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-A2rJT.framer-u5q2zy, .framer-A2rJT .framer-u5q2zy { display: block; }",
	".framer-A2rJT.framer-3rkuc9 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 180px; }",
	".framer-A2rJT .framer-172a42j { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-A2rJT.framer-3rkuc9 { gap: 0px; } .framer-A2rJT.framer-3rkuc9 > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-A2rJT.framer-3rkuc9 > :first-child { margin-left: 0px; } .framer-A2rJT.framer-3rkuc9 > :last-child { margin-right: 0px; } }",
];
var FramercribsgnSU = withCSS(Component, css, "framer-A2rJT");
var stdin_default = FramercribsgnSU;
FramercribsgnSU.displayName = "Cards/ Code animation";
FramercribsgnSU.defaultProps = {
	height: 170,
	width: 180,
};
addPropertyControls(FramercribsgnSU, {
	variant: {
		options: ["NUtWSUHgD", "GE4qRZXiM"],
		optionTitles: ["Text", "Empty"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramercribsgnSU,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Outfit",
					source: "fontshare",
					style: "normal",
					url: "https://framerusercontent.com/third-party-assets/fontshare/wf/HGVZO4W7MOWSOT5FITRR2LXJL4LPEVKA/JGNFYTACJN27RPO2O5AUTRRZD4FNRJPI/W7JHARPQSG6P4YAUJKIMUM6JNAX2RFW3.woff2",
					weight: "300",
				},
				{
					family: "Satoshi",
					source: "fontshare",
					style: "normal",
					url: "https://framerusercontent.com/third-party-assets/fontshare/wf/TTX2Z3BF3P6Y5BQT3IV2VNOK6FL22KUT/7QYRJOI3JIMYHGY6CH7SOIFRQLZOLNJ6/KFIAZD4RUMEZIYV6FQ3T3GP5PDBDB6JY.woff2",
					weight: "400",
				},
			],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/leh2tspMHyu9XprfMQNM/qxm65tw95UaQOxjkPHpt/S9RrCB1zs.js
var CardsCodeAnimationFonts = getFonts(stdin_default);
var serializationHash2 = "framer-D2dt4";
var variantClassNames2 = {
	zmkCPuLKT: "framer-v-1fvrqzm",
};
var transition12 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React2.Fragment);
var getProps2 = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo2();
	const { style, className, layoutId, variant, ...restProps } =
		getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		defaultVariant: "zmkCPuLKT",
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const ref1 = React2.useRef(null);
	const defaultLayoutId = React2.useId();
	const sharedStyleClassNames = [];
	const componentViewport = useComponentViewport2();
	return (
		<LayoutGroup2
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<motion2.div
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							serializationHash2,
							...sharedStyleClassNames,
							"framer-1fvrqzm",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"zmkCPuLKT"}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							backgroundColor:
								"var(--token-17c08985-425f-4b75-81e9-d1425ce278a8, rgba(255, 255, 255, 0.12))",
							borderBottomLeftRadius: 8,
							borderBottomRightRadius: 8,
							borderTopLeftRadius: 8,
							borderTopRightRadius: 8,
							mask: "linear-gradient(0deg, rgba(0,0,0,0) 0%, rgba(0, 0, 0, 0.43694) 27.477477477477475%, rgba(0,0,0,1) 100%) add",
							WebkitMask:
								"linear-gradient(0deg, rgba(0,0,0,0) 0%, rgba(0, 0, 0, 0.43694) 27.477477477477475%, rgba(0,0,0,1) 100%) add",
							...style,
						}}
					>
						<motion2.div
							className={"framer-hi9acm"}
							data-framer-name={"Top"}
							layoutDependency={layoutDependency}
							layoutId={"cBbQgRhV6"}
							style={{
								backgroundColor:
									"var(--token-667dfe34-ef33-4a0e-b107-e347ef5ffaa2, rgba(255, 255, 255, 0.15))",
							}}
						>
							<motion2.div
								className={"framer-1knmnoc"}
								data-framer-name={"Red dot"}
								layoutDependency={layoutDependency}
								layoutId={"yg5ACGoYa"}
								style={{
									backgroundColor: "rgba(255, 51, 51, 0.5)",
									borderBottomLeftRadius: 5,
									borderBottomRightRadius: 5,
									borderTopLeftRadius: 5,
									borderTopRightRadius: 5,
								}}
							/>
							<motion2.div
								className={"framer-nztzfz"}
								data-framer-name={"Yellow dot"}
								layoutDependency={layoutDependency}
								layoutId={"muZfcE1BM"}
								style={{
									backgroundColor: "rgba(230, 255, 0, 0.5)",
									borderBottomLeftRadius: 5,
									borderBottomRightRadius: 5,
									borderTopLeftRadius: 5,
									borderTopRightRadius: 5,
								}}
							/>
							<motion2.div
								className={"framer-1bwpf4r"}
								data-framer-name={"green dot"}
								layoutDependency={layoutDependency}
								layoutId={"vj8aV3rJh"}
								style={{
									backgroundColor: "rgba(51, 255, 78, 0.5)",
									borderBottomLeftRadius: 5,
									borderBottomRightRadius: 5,
									borderTopLeftRadius: 5,
									borderTopRightRadius: 5,
								}}
							/>
						</motion2.div>
						<motion2.div
							className={"framer-16o1hq1"}
							data-framer-name={"Main Content"}
							layoutDependency={layoutDependency}
							layoutId={"OweDVZl9t"}
						>
							<ComponentViewportProvider
								height={153}
								width={`max(${(componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.width) || "100vw"} - 10px, 1px)`}
								y={
									((componentViewport === null || componentViewport === void 0
										? void 0
										: componentViewport.y) || 0) +
									0 +
									20 +
									0
								}
							>
								<motion2.div
									className={"framer-gpn4f4-container"}
									layoutDependency={layoutDependency}
									layoutId={"AyaRNzBG3-container"}
								>
									{_jsx2(stdin_default, {
										height: "100%",
										id: "AyaRNzBG3",
										layoutId: "AyaRNzBG3",
										style: {
											height: "100%",
											width: "100%",
										},
										variant: "NUtWSUHgD",
										width: "100%",
									})}
								</motion2.div>
							</ComponentViewportProvider>
						</motion2.div>
					</motion2.div>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-D2dt4.framer-1nnau82, .framer-D2dt4 .framer-1nnau82 { display: block; }",
	".framer-D2dt4.framer-1fvrqzm { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 5px; height: 180px; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 200px; will-change: var(--framer-will-change-override, transform); }",
	".framer-D2dt4 .framer-hi9acm { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 5px; height: 15px; justify-content: flex-start; overflow: hidden; padding: 0px 10px 0px 10px; position: relative; width: 100%; }",
	".framer-D2dt4 .framer-1knmnoc, .framer-D2dt4 .framer-nztzfz, .framer-D2dt4 .framer-1bwpf4r { flex: none; height: 5px; overflow: hidden; position: relative; width: 5px; will-change: var(--framer-will-change-override, transform); }",
	".framer-D2dt4 .framer-16o1hq1 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px 5px 0px 5px; position: relative; width: 100%; }",
	".framer-D2dt4 .framer-gpn4f4-container { flex: 1 0 0px; height: 153px; position: relative; width: 1px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-D2dt4.framer-1fvrqzm, .framer-D2dt4 .framer-hi9acm, .framer-D2dt4 .framer-16o1hq1 { gap: 0px; } .framer-D2dt4.framer-1fvrqzm > * { margin: 0px; margin-bottom: calc(5px / 2); margin-top: calc(5px / 2); } .framer-D2dt4.framer-1fvrqzm > :first-child { margin-top: 0px; } .framer-D2dt4.framer-1fvrqzm > :last-child { margin-bottom: 0px; } .framer-D2dt4 .framer-hi9acm > * { margin: 0px; margin-left: calc(5px / 2); margin-right: calc(5px / 2); } .framer-D2dt4 .framer-hi9acm > :first-child, .framer-D2dt4 .framer-16o1hq1 > :first-child { margin-left: 0px; } .framer-D2dt4 .framer-hi9acm > :last-child, .framer-D2dt4 .framer-16o1hq1 > :last-child { margin-right: 0px; } .framer-D2dt4 .framer-16o1hq1 > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } }",
];
var FramerS9RrCB1zs = withCSS2(Component2, css2, "framer-D2dt4");
var stdin_default2 = FramerS9RrCB1zs;
FramerS9RrCB1zs.displayName = "Development card";
FramerS9RrCB1zs.defaultProps = {
	height: 180,
	width: 200,
};
addFonts2(
	FramerS9RrCB1zs,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...CardsCodeAnimationFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:development-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"03e84f604d558643c3b6be5341937b8855a6dbf7a820b887c6c5c1f3ad48ac5b"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders DevelopmentCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"03e84f604d558643c3b6be5341937b8855a6dbf7a820b887c6c5c1f3ad48ac5b"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var development_card_default = ComponentWithRoot;
export { development_card_default as default };
