// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 03e84f604d558643 "Radison (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * featureTitle?: string // feature title
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-SL3QGQ5O.js";
import { Icon } from "./chunks/chunk-IXDMRUES.js";
import "./chunks/chunk-BVM6H744.js";
import { routes } from "./chunks/chunk-HNSAVAZ4.js";

// virtual:pricing-plan-features
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/xP6CpO9TCOqm8HIjgg69/fDN01y1IssIUesJpZrsH/AqeMOsAGh.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var PhosphorFonts = getFonts(Icon);
var serializationHash = "framer-Xo44w";
var variantClassNames = {
	cRT3Hy1VH: "framer-v-uae1o2",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ featureTitle, height, id, width, ...props }) => {
	var _ref;
	return {
		...props,
		l_U6iR6Sk:
			(_ref =
				featureTitle !== null && featureTitle !== void 0
					? featureTitle
					: props.l_U6iR6Sk) !== null && _ref !== void 0
				? _ref
				: "Workflow automation",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		l_U6iR6Sk,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "cRT3Hy1VH",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [className];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							serializationHash,
							...sharedStyleClassNames,
							"framer-uae1o2",
							className2,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"cRT3Hy1VH"}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							...style,
						}}
					>
						<motion.div
							className={"framer-hu5zsp"}
							data-framer-name={"Icon holder"}
							layoutDependency={layoutDependency}
							layoutId={"UmAoBSRw1"}
							style={{
								backgroundColor:
									"var(--token-5e82b7fb-875b-478b-b151-baffd23609a0, rgba(255, 255, 255, 0.2))",
								borderBottomLeftRadius: 8,
								borderBottomRightRadius: 8,
								borderTopLeftRadius: 8,
								borderTopRightRadius: 8,
							}}
						>
							<ComponentViewportProvider>
								<motion.div
									className={"framer-1haeh4e-container"}
									layoutDependency={layoutDependency}
									layoutId={"UqwBaAavU-container"}
								>
									<Icon
										color={"rgb(255, 255, 255)"}
										height={"100%"}
										iconSearch={"check"}
										iconSelection={"House"}
										id={"UqwBaAavU"}
										layoutId={"UqwBaAavU"}
										mirrored={false}
										selectByList={false}
										style={{
											height: "100%",
											width: "100%",
										}}
										weight={"regular"}
										width={"100%"}
									/>
								</motion.div>
							</ComponentViewportProvider>
						</motion.div>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-52c9bs"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"gdunofW5W"}
							style={{
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							text={l_U6iR6Sk}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									className={"framer-styles-preset-19p2pli"}
									data-styles-preset={"vOdfG3utS"}
								>
									{"Workflow automation"}
								</motion.p>
							</React.Fragment>
						</RichText>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-Xo44w.framer-1xgc5uc, .framer-Xo44w .framer-1xgc5uc { display: block; }",
	".framer-Xo44w.framer-uae1o2 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 293px; }",
	".framer-Xo44w .framer-hu5zsp { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 5px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-Xo44w .framer-1haeh4e-container { flex: none; height: 15px; position: relative; width: 15px; }",
	".framer-Xo44w .framer-52c9bs { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-Xo44w.framer-uae1o2, .framer-Xo44w .framer-hu5zsp { gap: 0px; } .framer-Xo44w.framer-uae1o2 > *, .framer-Xo44w .framer-hu5zsp > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-Xo44w.framer-uae1o2 > :first-child, .framer-Xo44w .framer-hu5zsp > :first-child { margin-left: 0px; } .framer-Xo44w.framer-uae1o2 > :last-child, .framer-Xo44w .framer-hu5zsp > :last-child { margin-right: 0px; } }",
	...css,
];
var FramerAqeMOsAGh = withCSS(Component, css2, "framer-Xo44w");
var stdin_default = FramerAqeMOsAGh;
FramerAqeMOsAGh.displayName = "Pricing Plan features";
FramerAqeMOsAGh.defaultProps = {
	height: 25,
	width: 293,
};
addPropertyControls(FramerAqeMOsAGh, {
	l_U6iR6Sk: {
		defaultValue: "Workflow automation",
		displayTextArea: false,
		title: "feature title",
		type: ControlType.String,
	},
});
addFonts(
	FramerAqeMOsAGh,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...PhosphorFonts,
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:pricing-plan-features
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"03e84f604d558643c3b6be5341937b8855a6dbf7a820b887c6c5c1f3ad48ac5b"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders PricingPlanFeaturesFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"03e84f604d558643c3b6be5341937b8855a6dbf7a820b887c6c5c1f3ad48ac5b"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var pricing_plan_features_default = ComponentWithRoot;
export { pricing_plan_features_default as default };
